### ISSUE TITLE
如何看待腾讯的wujie方案

### ISSUE THREAD

**Issue by yanni4night** [lingjie-js/lingjie#2]
wujie方案声称使用了ShadowDOM解决了CSS隔离的问题，使用了iframe解决了JS沙箱的问题。是否可以将其看成是lingjie的拆分版本，将lingjie的视图部分渲染在了主应用内，JS同样都是跑在iframe当中？ @Lucifier129 工业聚怎么看？有助于开发者选型

**Comment by Lucifier129** [comment]
看了一下，无界侵入性更大一些，有 api，还得针对不同框架安装不同的包。

零界不需要，它可以无缝、无侵入、无框架要求。
